<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Faktum.ScreenMarker.Platform.Windows.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Faktum.ScreenMarker.Core\Faktum.ScreenMarker.Core.csproj" />
  </ItemGroup>

</Project>
